cache:
  paths:
    - node_modules/

stages:
  - init
  - test
  - deploy

init:
  stage: init
  image: node:10.8.0
  script:
    - npm install

test:
  stage: test
  image: node:10.8.0
  script:
    - npm run build  
    - CI=true npm test       

deploy:
  image: node:10.8.0
  stage: deploy
  script:
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/drp.git HEAD:master
  only:
    - master
