cache:
  paths:
    - /node_modules/

stages:
  - init
  - format
  - test
  - deploy

init:
  stage: init
  image: node:20.5.1
  script:
    - npm install

format:
  stage: format
  image: node:20.5.1
  script:
    - npx prettier . --check

test:
  stage: test
  image: node:20.5.1
  script:
    - npm run build
    - CI=true npm test

deploy:
  image: node:20.5.1
  stage: deploy
  script:
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/drp.git HEAD:master
  only:
    - master
